### ISSUE TITLE
HTTP_PORT - can you confirm this will move the internal port?

### ISSUE THREAD

**Issue by psyciknz** [leepeuker/movary#171]
Hi Again, so got it working with SQL Lite!! thanks.

So looking again at that HTTP_PORT env variable.
Here's my compose:
```
  movary:
    image: leepeuker/movary:latest
    container_name: movary
    dns:
      - 192.168.10.1
      - 192.168.10.237
    labels:
      - "autoheal=true"
      - com.centurylinklabs.watchtower.enable=true
      - caddy=*.internal.andc.nz
      - caddy.@movary=host movary.internal.andc.nz
      - caddy.route.1_reverse_proxy=@movary "{{ upstreams 95 }}"
    ports:
      - "8195:95"
      - "8198:80"
    networks:
      - media
      - caddy-proxy
    environment:
      HTTP_PORT: 95
      DATABASE_MODE: "sqlite"
      TMDB_API_KEY: "<key>"
    volumes:
      - movary-storage:/app/storage
```

This is to work with those labels to get the web site running on port 80 to port 95.  But now ignoring the reverse proxying, when it's running if I try to connect to the mapped 95 port, I get nothing.  However with this config, if I go to where port 80 is mapped, the site is up.

I can see the HTTP_PORT env variable in the container and set to 95.

I don't know enough PHP and how this is starting up a web server to confirm if this is going to work or not.  But at least iI can now press on.  Looking very nice.

EDIT: oh an done quick other thing, normally 2nd restart gets this error:
```
movary           | error: failed switching to "root": operation not permitted
```
Normalyl I have to destroy container and create
