### ISSUE TITLE
Fails to initiate SQLite on first launch

### ISSUE THREAD

**Issue by filcuk** [leepeuker/movary#233]
Latest version won't start, database not created:
```
PHP Fatal error:  Uncaught Exception: Unable to open database: unable to open database file in /app/vendor/doctrine/dbal/src/Driver/SQLite3/Driver.php:35
```
Full log: [movary_log.txt](https://github.com/leepeuker/movary/files/10418318/_movary_logs.2.txt)

My compose:
```yaml
  movary:
    image: leepeuker/movary:latest
    container_name: movary
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      TIMEZONE: $TZ
      ENV: production
      DATABASE_MODE: "sqlite"
      TMDB_API_KEY: ${TMDB_API_KEY:?}
      TMDB_ENABLE_IMAGE_CACHING: 1  # Enable to prevent rate limit issues
      LOG_LEVEL: warning
      LOG_ENABLE_STACKTRACE: 0
      LOG_ENABLE_FILE_LOGGING: 1  # Log directory is at `storage/logs`
    volumes:
      - $DOCKERDIR/appdata/movary:/app/storage
```

I've tried adding `user: ...` and have ensured the folder is owned by the docker user, but no change.

**Comment by leepeuker** [comment]
Hey, sorry for your issue. The easiest way to solve this would usually be to use a docker volume to persist the storage data instead of mounting the storage directory to the host. If you want to mount check out [this](https://github.com/leepeuker/movary/issues/229#issuecomment-1381845326) comment. In short: Create the `app/public` directory in your storage mount if it does not already exist and **recreate** the container.

**Comment by filcuk** [comment]
Thanks for the quick response!

I would mention that my setup should tick all the boxes in your linked comment, i.e.:
> mounting storage directly to the host works when the new required directory `<storagepath>/app/public` already exist on the host. Create this directory manually and recreate the container (important, e.g. with `--force-recreate flag`). You may have to set user/group id of the container via e.g. `--user 1000:1000` to match the host storage directory owner.
- mounted dir already exists
- `user: $PUID:$PGID` for the dir owner (docker user) was added to the service (folder was `chown`ed too, just in case)
- container was recreated on each attempt
---
Regardless, as you recommended, using docker volume solves that issue:
```yaml
services:
  movary:
    ...
    volumes:
      - movary:/app/storage
    ...
volumes:
  movary:
```

However, now when I run the command to initialise (`docker exec movary php bin/console.php database:migration:migrate`), it reports that the database is read-only:
```
InvalidArgumentException: There was a problem creating the schema table: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database in /app/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php:318
```
I've tried explicitly stating `movary:/app/storage:rw`, but that didn't help either.

Could the database be `ro` because movary is trying to run a job on the database that hasn't been initialised yet?
Please see this log: [movary_log_2.txt](https://github.com/leepeuker/movary/files/10418611/_movary_logs.3.txt)
```
movary.ERROR: Could not process job. {"exception":"[object] (Doctrine\\DBAL\\Exception\\TableNotFoundException(code: 0): An exception occurred while executing a query: Unable to prepare statement: 1, no such table: job_queue at /app/vendor/doctrine/dbal/src/Driver/API/SQLite/ExceptionConverter.php:52)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\SQLite3\\Exception(code: 0): Unable to prepare statement: 1, no such table: job_queue at /app/vendor/doctrine/dbal/src/Driver/SQLite3/Exception.php:16)\n[previous exception] [object] (Exception(code: 0): Unable to prepare statement: 1, no such table: job_queue at /app/vendor/doctrine/dbal/src/Driver/SQLite3/Connection.php:25)"} []
```

**Comment by filcuk** [comment]
I've got it running now.
I've had to remove the previously added `user: $PUID:$PGID`.

Just for reference, my final compose looks like this:
```yaml
services:
  movary:
    image: leepeuker/movary:latest
    container_name: movary
    restart: "no"
    ports:
      - "8712:80"
    environment:
      TIMEZONE: $TZ
      ENV: production
      DATABASE_MODE: "sqlite"
      TMDB_API_KEY: ${TMDB_API_KEY:?}
      TMDB_ENABLE_IMAGE_CACHING: 1  # Enable to prevent rate limit issues
      LOG_LEVEL: warning
      LOG_ENABLE_STACKTRACE: 0
      LOG_ENABLE_FILE_LOGGING: 1  # Log directory is at `storage/logs`
      MIN_RUNTIME_IN_SECONDS_FOR_JOB_PROCESSING: 15 # Min time between jobs
    volumes:
      - movary-vol:/app/storage
volumes:
  movary-vol:
    external: true
```

Thanks for your help!
