### ISSUE TITLE
Unable to start container

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#347]
When starting Movary as a docker container, the following errors appear in the logs:

```
2023-05-16 18:49:59,566 INFO spawned: 'movary' with pid 90
PHP Warning:  PHP Startup: Unable to load dynamic library 'imagick.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so (Error loading shared library libgomp.so.1: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imagick.so.so: No such file or directory)) in Unknown on line 0
PHP Fatal error:  Uncaught RuntimeException: Not supported database mode: "mysql" in /app/src/Factory.php:144
Stack trace:
#0 [internal function]: Movary\Factory::createDbConnection(Object(Movary\ValueObject\Config))
#1 /app/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#2 /app/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(69): Invoker\Invoker->call(Array, Array)
#3 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#4 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array)
#5 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition))
#6 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Doctrine\\DBAL\\C...')
#7 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#8 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#9 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#10 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#11 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#12 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#13 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#14 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Api\\Trak...')
#15 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#16 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#17 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#18 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#19 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#20 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#21 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#22 /app/src/Factory.php(274): DI\Container->get('Movary\\Api\\Trak...')
#23 [internal function]: Movary\Factory::createTraktApi(Object(DI\Container))
#24 /app/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#25 /app/vendor/php-di/php-di/src/Definition/Resolver/FactoryResolver.php(69): Invoker\Invoker->call(Array, Array)
#26 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\FactoryResolver->resolve(Object(DI\Definition\FactoryDefinition), Array)
#27 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\FactoryDefinition), Array)
#28 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\FactoryDefinition))
#29 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Api\\Trak...')
#30 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#31 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#32 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#33 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#34 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#35 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#36 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#37 /app/vendor/php-di/php-di/src/Definition/Reference.php(44): DI\Container->get('Movary\\Service\\...')
#38 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(55): DI\Definition\Reference->resolve(Object(DI\Container))
#39 /app/vendor/php-di/php-di/src/Definition/Resolver/ParameterResolver.php(73): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\Reference))
#40 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(123): DI\Definition\Resolver\ParameterResolver->resolveParameters(Object(DI\Definition\ObjectDefinition\MethodInjection), Object(ReflectionMethod), Array)
#41 /app/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(56): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#42 /app/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(60): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#43 /app/vendor/php-di/php-di/src/Container.php(356): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#44 /app/vendor/php-di/php-di/src/Container.php(136): DI\Container->resolveDefinition(Object(DI\Definition\ObjectDefinition))
#45 /app/bin/console.php(7): DI\Container->get('Movary\\Command\\...')
#46 {main}
  thrown in /app/src/Factory.php on line 144
2023-05-16 18:49:59,753 WARN exited: movary (exit status 255; not expected)
2023-05-16 18:50:00,755 INFO gave up: movary entered FATAL state, too many start retries too quickly
```
Why does it show an error about Imagick? I didn't know Movary needed that.
And why is mysql suddenly an unsupported database type?

**Comment by JVT038** [comment]
My `docker-compose.yml`:
```yaml
version: "3.8"

networks:
  traefik:
    external:
      name: traefik_proxy
  

services:
  movary:
    image: leepeuker/movary:latest
    container_name: movary
    networks:
      - traefik
      - default
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
      - DATABASE_MODE="mysql"
      - DATABASE_MYSQL_HOST="mysql"
      - DATABASE_MYSQL_NAME="movary"
      - DATABASE_MYSQL_USER="movary_user"
      - DATABASE_MYSQL_PASSWORD=$MYSQL_MOVARY_PASSWORD
      - TIMEZONE=$TZ
      - APPLICATION_URL=movary.$DOMAINNAME
    volumes:
      - $DOCKERDIR/movary/storage:/app/storage
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.movary-rtr.entrypoints=https"
      - "traefik.http.routers.movary-rtr.rule=Host(`movary.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.movary-rtr.middlewares=chain-basic-lan@file"
      ## HTTP Services
      - "traefik.http.routers.movary-rtr.service=movary-svc"
      - "traefik.http.services.movary-svc.loadbalancer.server.port=80"

  mysql:
    image: mysql:8.0
    container_name: movary_mysql
    networks:
      - default
    environment:
      - MYSQL_DATABASE="movary"
      - MYSQL_USER="movary_user"
      - MYSQL_PASSWORD=$MYSQL_MOVARY_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_MOVARY_ROOT_PASSWORD
    volumes:
      - $DOCKERDIR/movary/database:/var/lib/mysql
```
