### ISSUE TITLE
exec /entrypoint: exec format error

### ISSUE THREAD

**Issue by navilg** [leepeuker/movary#523]
### Description

I am getting error `exec /entrypoint: exec format error` when installing using docker compose.

My docker-compose file is as below:

```
version: "3.9"
services:
  movary:
    image: leepeuker/movary:0.58.0
    container_name: movary
    environment:
      TMDB_API_KEY: "${TMDB_API_KEY}"
      DATABASE_MODE: "sqlite"
      TIMEZONE: "UTC"
      APPLICATION_URL: "${DOMAIN}"
      TMDB_ENABLE_IMAGE_CACHING: "1"
    volumes:
      - movary-storage:/app/storage
    networks:
      - mynetwork
    labels:
      - traefik.enable=true
      - traefik.http.routers.movary.entrypoints=websecure
      - traefik.http.routers.movary.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.movary.tls=true
      - traefik.http.routers.movary.tls.certresolver=le
      - traefik.http.routers.movary.tls.domains[0].main=${DOMAIN}
      - traefik.http.services.movary.loadbalancer.server.port=80
volumes:
  movary-storage:
networks:
  mynetwork:
    external: true
```

### Version

0.58.0

### Steps to Reproduce

Deploy using docker compose

### Client Platform

None
