### ISSUE TITLE
Container Healthcheck fails on version 0.64.0

### ISSUE THREAD

**Issue by samcro1967** [leepeuker/movary#634]
### Description

URL for container healthcheck needs to be updated to reflect the change in internal port with this release.
**From:**
`curl --silent --fail http://127.0.0.1/fpm-ping || exit 1`

**To:**
`curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1`

### Version

0.64.0

### Steps to Reproduce

Run version  0.64.0

### Logs

```shell

```

### Client Platform

None

**Comment by bunkerman** [comment]
I also have this problem

**Comment by samcro1967** [comment]
@bunkerman For now you can override the container healthcheck by adding the below to your docker compose for movary until the container is updated.  I needed to stop it from becoming unhealthy so that my automation would stop kicking in every couple of mins to alert me it was unhealthy and being restarted to try and self heal it.

```
    healthcheck:
      test: curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
```
